// Code generated by protoc-gen-go. DO NOT EDIT.
// source: renderer.proto

package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RendererParams struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Lang                 string   `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RendererParams) Reset()         { *m = RendererParams{} }
func (m *RendererParams) String() string { return proto.CompactTextString(m) }
func (*RendererParams) ProtoMessage()    {}
func (*RendererParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_renderer_5955fb46de12f934, []int{0}
}
func (m *RendererParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RendererParams.Unmarshal(m, b)
}
func (m *RendererParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RendererParams.Marshal(b, m, deterministic)
}
func (dst *RendererParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RendererParams.Merge(dst, src)
}
func (m *RendererParams) XXX_Size() int {
	return xxx_messageInfo_RendererParams.Size(m)
}
func (m *RendererParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RendererParams.DiscardUnknown(m)
}

var xxx_messageInfo_RendererParams proto.InternalMessageInfo

func (m *RendererParams) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RendererParams) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

type RendererResponse struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	RedirectTo           string   `protobuf:"bytes,3,opt,name=redirect_to,json=redirectTo,proto3" json:"redirect_to,omitempty"`
	RenderedHead         []byte   `protobuf:"bytes,4,opt,name=rendered_head,json=renderedHead,proto3" json:"rendered_head,omitempty"`
	RenderedBody         []byte   `protobuf:"bytes,5,opt,name=rendered_body,json=renderedBody,proto3" json:"rendered_body,omitempty"`
	RenderedStyles       []byte   `protobuf:"bytes,6,opt,name=rendered_styles,json=renderedStyles,proto3" json:"rendered_styles,omitempty"`
	RenderedScripts      []byte   `protobuf:"bytes,7,opt,name=rendered_scripts,json=renderedScripts,proto3" json:"rendered_scripts,omitempty"`
	Ttr                  int32    `protobuf:"varint,8,opt,name=ttr,proto3" json:"ttr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RendererResponse) Reset()         { *m = RendererResponse{} }
func (m *RendererResponse) String() string { return proto.CompactTextString(m) }
func (*RendererResponse) ProtoMessage()    {}
func (*RendererResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_renderer_5955fb46de12f934, []int{1}
}
func (m *RendererResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RendererResponse.Unmarshal(m, b)
}
func (m *RendererResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RendererResponse.Marshal(b, m, deterministic)
}
func (dst *RendererResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RendererResponse.Merge(dst, src)
}
func (m *RendererResponse) XXX_Size() int {
	return xxx_messageInfo_RendererResponse.Size(m)
}
func (m *RendererResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RendererResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RendererResponse proto.InternalMessageInfo

func (m *RendererResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RendererResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RendererResponse) GetRedirectTo() string {
	if m != nil {
		return m.RedirectTo
	}
	return ""
}

func (m *RendererResponse) GetRenderedHead() []byte {
	if m != nil {
		return m.RenderedHead
	}
	return nil
}

func (m *RendererResponse) GetRenderedBody() []byte {
	if m != nil {
		return m.RenderedBody
	}
	return nil
}

func (m *RendererResponse) GetRenderedStyles() []byte {
	if m != nil {
		return m.RenderedStyles
	}
	return nil
}

func (m *RendererResponse) GetRenderedScripts() []byte {
	if m != nil {
		return m.RenderedScripts
	}
	return nil
}

func (m *RendererResponse) GetTtr() int32 {
	if m != nil {
		return m.Ttr
	}
	return 0
}

func init() {
	proto.RegisterType((*RendererParams)(nil), "internal.RendererParams")
	proto.RegisterType((*RendererResponse)(nil), "internal.RendererResponse")
}

func init() { proto.RegisterFile("renderer.proto", fileDescriptor_renderer_5955fb46de12f934) }

var fileDescriptor_renderer_5955fb46de12f934 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0xd5, 0x3f, 0x29, 0xe5, 0x28, 0x25, 0xb2, 0x18, 0xbc, 0x51, 0x95, 0x81, 0xb2, 0xb0,
	0x20, 0xf1, 0x00, 0xb0, 0x30, 0x22, 0x97, 0x3d, 0x72, 0x73, 0x27, 0x88, 0x14, 0x7c, 0xd1, 0xf9,
	0x3a, 0xe4, 0x55, 0x78, 0x5a, 0x14, 0x27, 0x29, 0xea, 0x76, 0xfe, 0xf9, 0x77, 0x9f, 0x74, 0x1f,
	0xac, 0x85, 0x02, 0x92, 0x90, 0x3c, 0x35, 0xc2, 0xca, 0x66, 0x59, 0x05, 0x25, 0x09, 0xbe, 0xde,
	0xbe, 0xc0, 0xda, 0x0d, 0x7f, 0x1f, 0x5e, 0xfc, 0x4f, 0x34, 0x39, 0xcc, 0x8e, 0x52, 0xdb, 0xc9,
	0x66, 0xb2, 0xbb, 0x74, 0xdd, 0x68, 0x0c, 0xcc, 0x6b, 0x1f, 0xbe, 0xec, 0x34, 0xa1, 0x34, 0x6f,
	0x7f, 0xa7, 0x90, 0x8f, 0x8b, 0x8e, 0x62, 0xc3, 0x21, 0x92, 0xb9, 0x83, 0xab, 0xa8, 0x5e, 0x8f,
	0xb1, 0x28, 0x19, 0x29, 0x45, 0x64, 0x0e, 0x7a, 0xf4, 0xc6, 0x48, 0xe6, 0x16, 0x32, 0x12, 0x61,
	0x19, 0xa2, 0xfa, 0x47, 0xb7, 0x26, 0x84, 0x95, 0x50, 0xa9, 0x85, 0xb2, 0x9d, 0xa5, 0x3f, 0x18,
	0xd1, 0x27, 0x9b, 0x7b, 0xb8, 0x1e, 0x0e, 0xc0, 0xe2, 0x9b, 0x3c, 0xda, 0xf9, 0x66, 0xb2, 0x5b,
	0xb9, 0xd5, 0x08, 0xdf, 0xc9, 0xe3, 0x99, 0x74, 0x60, 0x6c, 0x6d, 0x76, 0x2e, 0xbd, 0x32, 0xb6,
	0xe6, 0x01, 0x6e, 0x4e, 0x52, 0xd4, 0xb6, 0xa6, 0x68, 0x17, 0x49, 0x1b, 0x1b, 0xc2, 0x7d, 0xa2,
	0xe6, 0x11, 0xf2, 0x7f, 0xb1, 0x94, 0xaa, 0xd1, 0x68, 0x2f, 0x92, 0x79, 0x0a, 0xd8, 0xf7, 0xb8,
	0x2b, 0x4c, 0x55, 0xec, 0x32, 0x5d, 0xdb, 0x8d, 0x87, 0x45, 0x6a, 0xf9, 0xf9, 0x2f, 0x00, 0x00,
	0xff, 0xff, 0x50, 0x53, 0x1d, 0x91, 0x77, 0x01, 0x00, 0x00,
}
